### ISSUE TITLE
Incorrect NEXUS_CONTEXT environment variable makes Nexus docker repositories inaccessible (error 404)

### ISSUE THREAD

**Issue by n-g-work** [epam/edp-nexus-operator#1]
**What happened**:

Docker repositories created in Nexus are inaccessible with HTTP error 404.

**What you expected to happen**:

When docker repositories are created in Nexus they should be available for `curl "${nexus_url}/v2/_catalog"` and `docker push/pull` commands.

**How to reproduce it (as minimally and precisely as possible)**:

Create a docker repository in Nexus, that was deployed as a part of EDP.
Try to get the new repository's catalog with `curl "${nexus_url}/v2/_catalog"`
The response would be HTTP error 404.

**Anything else we need to know?**:

The issue is in the NEXUS_CONTEXT environment variable, which is filled with "//" (double forward slash) rather than the correct "/" (a single forward slash).

The defect happens due to the first forward slash introduced in the Nexus' default properties ConfigMap:
https://github.com/epam/edp-nexus-operator/blob/master/deploy-templates/templates/cm/configuration/nexus_default.properties.yaml#L9

And the second forward slash is specified in both the Deployment for Kubernetes and DeploymentConfig for OpenShift:
https://github.com/epam/edp-nexus-operator/blob/master/deploy-templates/templates/deployment/nexus_deployment_kubernetes.yaml#L37
https://github.com/epam/edp-nexus-operator/blob/master/deploy-templates/templates/deployment/nexus_deployment_config_openshift.yaml#L39

**Environment**:

- Platform (e.g: `cat /etc/os-release`): Kubernetes and OpenShift
- EDP version: All
- Nexus Operator version: 2.5.0-RC.1 - 2.13.0
- Others: -

**Comment by NikolayMarusenko** [comment]
Hi! Thank you for your feedback!
We took issue into work.
We will provide details of the solution as we progress.

**Comment by n-g-work** [comment]
Maybe the easiest way to confirm the issue is to run helm template command:

`helm template edp epamedp/edp-install --set global.webConsole.url=example.local --set awsRegion=none | grep NEXUS_CONTEXT -A1`

Which gives this output:
```
    nexus-context-path=/${NEXUS_CONTEXT}

--
            - name: NEXUS_CONTEXT
              value: "/"
```

Even when the basePath is specified for Nexus, the result is wrong. The following command shows that the env variable value is doubled:

`helm template edp epamedp/edp-install --set global.webConsole.url=example.local --set nexus-operator.nexus.basePath=/some/path --set awsRegion=none | grep NEXUS_CONTEXT -A1`

Output:
```
    nexus-context-path=/${NEXUS_CONTEXT}

--
            - name: NEXUS_CONTEXT
              value: "/some/path/some/path"
```

This behavior can be found in all versions of the edp-install chart, including 2.12 and 3.x.

**Comment by NikolayMarusenko** [comment]
@n-g-work We've fixed the issue in master branch. You can use the master branch for chart installation. We will release a new stable version in a few weeks.
