### ISSUE TITLE
Add label for nexus-ci.user secret provisioning

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-nexus-operator#2]
Headlamp UI use label to find and display secrets for integration with Nexus.

Acceptance Criteria:

- nexus-operator create nexus-ci.user secret with label "app.edp.epam.com/secret-type: nexus";

**Comment by SergK** [comment]
Implemented



![Image](https://github.com/epam/edp-nexus-operator/assets/1520525/33c4d74d-98bb-4930-825b-5db4c764ac8f)
